name: game-of-life

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh to pull latest version
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo su gameoflife
            cd ~/Game-of-life
            git pull origin main
            yarn install
            forever restart -c "yarn start" .
          host: memowall.duncantang.dev
          user: ubuntu
          key: ${{secrets.SSH_PRIVATE_KEY}}